name: compile-and-run
on: [push]

jobs:
  check-versions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
#      - name: Use GCC 10 instead
#        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
      - run: sudo apt-get install ninja-build
      - run: gcc --version && g++ --version && ninja --version
      - name: Setup build
        run: |
            mkdir -p build
            cd build
            cmake .. -G Ninja -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
      - name: Build
        run: |
            cd build
            cmake --build .
      - name: Run
        run: |
            cd build
            ./ActionsTest
