name: compile-and-run
on: [push]

jobs:
  check-versions:
    strategy:
      matrix:
        include:
          - cpp-compiler: g++-10
            c-compiler: gcc-10
          - cpp-compiler: clang++-10
            c-compiler: clang-10
    env:
      build_folder_location: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install ninja-build
      - run: gcc --version && g++ --version && ninja --version
      - name: Setup build
        run: |
            mkdir -p ${{ env.build_folder_location }}
            cd ${{ env.build_folder_location }}
            cmake .. -G Ninja -DCMAKE_C_COMPILER=${{ matrix.c-compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp-compiler }}
      - name: Build
        run: |
            cd ${{ env.build_folder_location }}
            cmake --build .
      - name: Run
        run: |
            cd ${{ env.build_folder_location }}
            ./ActionsTest
      - name: Check clang
        run: clang++-9 --version
      - name: Check clang 2
        run: clang++-10 --version

